version: '3.8'
services:
  postgres:
    image: postgres:10.3
    container_name: DB-container
    restart: always
    environment:
      - POSTGRES_USER=sammy
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_DB=dp1
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5434:5432'
    networks:
      - somenetwork

volumes:
  postgres:


networks:
  somenetwork:
    driver: bridge
